import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marketing Copy AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl text-center font-bold text-indigo-500 underline">
          Hello World
        </h1>
      </main>
    </>
  );
}
